export interface Item {
  id: number,
  deleted?: boolean,
  type: "job" | "story" | "comment" | "poll" | "pollopt",
  by?: string,
  time?: number,
  text?: string,
  dead?: boolean,
  title?: string,
  descendants?: number,
  parts?: number[],
  kids?: number[],
  url?: string,
  score?: number,
  parent?: number,
  poll?: number,
}
